# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  pool: 5

development:
  <<: *default
  database: lenders_borrowers_development


test:
  <<: *default
  database: lenders_borrowers_test


production:
  <<: *default
  database: lenders_borrowers_production
  password: <%= ENV['LENDERS_BORROWERS_DATABASE_PASSWORD'] %>
